image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login -u $DO_REGISTRY_USER -p $DO_REGISTRY_PASSWORD $DO_REGISTRY

build:
  stage: build
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $DO_REGISTRY/$CI_PROJECT_PATH:latest
    - docker build -t $DO_REGISTRY/doctl:latest .
