image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - build
  - deploy
before_script: 
  - docker login -u $DO_REGISTRY_USER -p $DO_REGISTRY_PASSWORD $DO_REGISTRY

build_container:
  stage: build
  script:
    - docker login -u $DO_REGISTRY_USER -p $DO_REGISTRY_PASSWORD $DO_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $DO_REGISTRY/$CI_PROJECT_PATH:latest
    - docker build -t $DO_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker push $DO_REGISTRY/$CI_PROJECT_PATH:latest
  tags:
    - cluster

deploy_test:
  image: 
    name: $DO_REGISTRY/$CI_PROJECT_PATH:latest
    entrypoint: [""]
  stage: deploy
  script:
    - doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
    - doctl kubernetes cluster kubeconfig save sgan-k8s
    - kubectl get pods -n default
  tags:
    - cluster
