
pool: PodmanAgents
variables:
  - name: containerPath
    value: sgan/containers/core
  - group: DigitalOcean
  - group: usvoters_pg
trigger:
- master

stages:
  - stage: DeployDoctlContainer
    displayName: Deploy doctl_container
    jobs:
      - deployment: DeploymentForDoctlContainer
        displayName: Build and Push for doctl_container
        environment: digitalocean
        pool: PodmanAgents
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .template.yml
